[workspace]
members = [
    "conjure-codegen",
    "conjure-rust",
    "conjure-serde",
    "conjure-test",
    "conjure",
]

[patch.crates-io]
# hack for MUSL builds
proc-macro2 = { git = "https://github.com/sfackler/proc-macro2" }
quote = { git = "https://github.com/sfackler/quote" }
