version: 2.1

executors:
  rust:
    docker:
      - image: rust:1.31.1

jobs:
  checkout:
    executor: rust
    steps:
      - checkout
      - restore_cache:
          key: registry
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ .BuildNum }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          key: deps-{{ checksum "Cargo.lock" }}
      - run: cargo fetch
      - save_cache:
          key: deps-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry/cache
            - /usr/local/cargo/registry/src
      - persist_to_workspace:
          root: /
          paths:
            - root/project
            - usr/local/cargo/registry

  test:
    executor: rust
    environment:
      RUSTFLAGS: -D warnings
    steps:
      - attach_workspace:
          at: /
      - run: rustup component add clippy rustfmt
      - run: rustc --version > ~/rust-version
      - restore_cache:
          key: test-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
      - run: cargo clippy --all
      - run: cargo fmt --all -- --check
      - run: cargo test --all --all-features
      - save_cache:
          key: test-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
          paths:
            - target

  dist-linux:
    executor: rust
    steps:
      - attach_workspace:
          at: /
      - run: apt-get update
      - run: apt-get install -y musl-tools
      - run: rustup update beta
      - run: rustup default beta
      - run: rustup target add --toolchain beta x86_64-unknown-linux-musl
      - run: rustc --version > ~/rust-version
      - restore_cache:
          key: dist-linux-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
      - run: cargo build --release --target x86_64-unknown-linux-musl -p conjure-rust
      - run: strip target/x86_64-unknown-linux-musl/release/conjure-rust
      - save_cache:
          key: dist-linux-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
          paths:
            - target
      - persist_to_workspace:
          root: /
          paths: root/project/target/x86_64-unknown-linux-musl/release/conjure-rust

  dist-macos:
    macos:
      xcode: 10.1.0
    environment:
      RUSTUP_HOME: /Users/distiller/usr/local/rustup
      CARGO_HOME: /Users/distiller/usr/local/cargo
    working_directory: /Users/distiller/root/project
    steps:
      - attach_workspace:
          at: /Users/distiller
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain beta
      - run: sudo ln -s $CARGO_HOME/bin/* /usr/local/bin
      - run: rustc --version > ~/rust-version
      - restore_cache:
          key: dist-macos-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
      - run: cargo build --release --target x86_64-apple-darwin -p conjure-rust
      - run: strip target/x86_64-apple-darwin/release/conjure-rust
      - save_cache:
          key: dist-macos-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
          paths:
            - target
      - persist_to_workspace:
          root: /Users/distiller
          paths: root/project/target/x86_64-apple-darwin/release/conjure-rust

  dist-publish:
    executor: rust
    steps:
      - attach_workspace:
          at: /
      - run: |
          name="conjure-rust-$(git describe --tags --always)"
          base=$(mktemp -d)
          bin=$base/$name/bin
          mkdir -p $bin
          for arch in x86_64-unknown-linux-musl x86_64-apple-darwin; do
            mkdir $bin/$arch
            cp target/$arch/release/conjure-rust $bin/$arch
          done
          cp .circleci/conjure-rust $bin
          tar cvzf /tmp/$name.tgz -C $base $name

          mkdir ~/artifacts
          cp /tmp/$name.tgz ~/artifacts
      - store_artifacts:
          path: ~/artifacts

workflows:
  version: 2
  main:
    jobs:
      - checkout
      - test: { requires: [checkout] }
      - dist-linux: { requires: [checkout] }
      - dist-macos: { requires: [checkout] }
      - dist-publish: { requires: [dist-linux, dist-macos] }
