version: 2
jobs:
  checkout:
    docker:
      - image: rust:1.31.1-slim
    steps:
      - checkout
      - restore_cache:
          key: registry
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ .BuildNum }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          key: deps-{{ checksum "Cargo.lock" }}
      - run: cargo fetch
      - save_cache:
          key: deps-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry/cache
            - /usr/local/cargo/registry/src
      - persist_to_workspace:
          root: /
          paths:
            - root/project
            - usr/local/cargo/registry

  test:
    docker:
      - image: rust:1.31.1-slim
    environment:
      RUSTFLAGS: -D warnings
    steps:
      - attach_workspace:
          at: /
      - run: rustup component add clippy rustfmt
      - run: rustc --version > ~/rust-version
      - restore_cache:
          key: test-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
      - run: cargo clippy --all
      - run: cargo fmt --all -- --check
      - run: cargo test --all
      - save_cache:
          key: test-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
          paths:
            - target

  dist-linux:
    docker:
      - image: rust:1.31.1-slim
    steps:
      - attach_workspace:
          at: /
      - run: apt-get update
      - run: apt-get install -y musl-tools
      - run: rustup update beta
      - run: rustup target add --toolchain beta x86_64-unknown-linux-musl
      - run: rustc +beta --version > ~/rust-version
      - restore_cache:
          key: dist-linux-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
      - run: cargo +beta build --release --target x86_64-unknown-linux-musl -p conjure-rust
      - run: strip target/x86_64-unknown-linux-musl/release/conjure-rust
      - save_cache:
          key: dist-linux-target-{{ checksum "Cargo.lock" }}-{{ checksum "~/rust-version" }}
          paths:
            - target
      - persist_to_workspace:
          root: /
          paths: root/project/target/x86_64-unknown-linux-musl/release/conjure-rust

workflows:
  version: 2
  main:
    jobs:
      - checkout
      - test: { requires: [checkout] }
      - dist-linux: { requires: [checkout] }
