[package]
name = "conjure-test"
version = "0.1.2"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
conjure-object = { path = "../conjure-object" }

[dev-dependencies]
serde_json = "1.0"
base64 = "0.10"

conjure-serde = { path = "../conjure-serde" }

[build-dependencies]
conjure-codegen = { path = "../conjure-codegen" }
