[package]
name = "conjure-error"
version = "0.3.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde-value = "0.5"

conjure-object = { version = "0.3.0", path = "../conjure-object" }
